### ISSUE TITLE
Implement Projects Functionality

### ISSUE THREAD

**Issue by saidghamra** [AgoraCloud/server#31]
# Description
We need to implement project (tasks) functionality.

At a high level, the AgoraCloud projects functionality will be composed of the following:

**Projects**
- Each workspace can have zero to many projects
- Same concept as GitHub projects

**Lanes**
- Each project can have one to many lanes
- A lane represents a column in a project board, such as `To Do`, `Doing` and `Done`

**Tasks**
- A task can only belong to one lane and one project

# REST APIs
## Projects

| API                                       | Method | Description                                                         |
| ----------------------------------------- | :----: | ------------------------------------------------------------------- |
| /api/workspaces/:workspaceId/projects   |  GET   | Get all the users projects in the given workspace              |
| /api/workspaces/:workspaceId/projects/:id |  GET   | Get the users projects with the given id in the given workspace |
| /api/workspaces/:workspaceId/projects    |  POST  | Create a project in the given workspace                        |
| /api/workspaces/:workspaceId/projects/:id |  PUT   | Update a project with the given id in the given workspace      |
| /api/workspaces/:workspaceId/projects/:id | DELETE | Delete a project with the given id in the given workspace      |

## Lanes

| API                                       | Method | Description                                                         |
| ----------------------------------------- | :----: | ------------------------------------------------------------------- |
| /api/workspaces/:workspaceId/projects/:projectId/lanes  |  GET   | Get all the lanes in the given project and workspace              |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:id |  GET   | Get the lane with the given id in the given project and workspace |
| /api/workspaces/:workspaceId/projects/:projectId/lanes    |  POST  | Create a lane in the given project and workspace                        |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:id |  PUT   | Update a lane with the given id in the given project and workspace      |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:id | DELETE | Delete a lane with the given id in the given project and workspace      |

## Tasks

| API                                       | Method | Description                                                         |
| ----------------------------------------- | :----: | ------------------------------------------------------------------- |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:laneId/tasks  |  GET   | Get all the tasks in the given project lane and workspace              |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:laneId/tasks/:id |  GET   | Get the task with the given id in the given project lane and workspace |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:laneId/tasks    |  POST  | Create a task in the given project lane and workspace                        |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:laneId/tasks/:id |  PUT   | Update a task with the given id in the given project lane and workspace      |
| /api/workspaces/:workspaceId/projects/:projectId/lanes/:laneId/tasks/:id | DELETE | Delete a task with the given id in the given project lane and workspace      |

# To Do

**Projects**
- [x] Create ProjectsModule
- [x] Create and implement ProjectsController
- [x] Create and implement ProjectsService

**Lanes**
- [x] Create ProjectLanesModule
- [x] Create and implement ProjectLanesController
- [x] Create and implement ProjectLanesService

**Tasks**
- [x] Create ProjectTasksModule
- [x] Create and implement ProjectTasksController
- [x] Create and implement ProjectTasksService

**Testing**
- [x] Test ProjectsService
- [x] Test ProjectLanesService
- [x] Test ProjectTasksService

**Documentation**
- [x] Add `project.created` event
- [x] Add `project.deleted` event
- [x] Add `project.lane.deleted` event
- [x] Add projects REST APIs description
- [x] Add lanes REST APIs description
- [x] Add tasks REST APIs description

**Comment by saidghamra** [comment]
In `Develop`
